name: K8s Yaml Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: azure/k8s-lint@v1
        with:
          lintType: dryrun
          manifests: |
              ./*.yaml

